### ISSUE TITLE
object is not a function

### ISSUE THREAD

**Issue by jekkihun** [soulwu/yuntongxun#7]
var yuntongxun = new Yuntongxun({
                 ^
TypeError: object is not a function

**Comment by soulwu** [comment]
from babel6, `export default Yuntongxun` transformd to `exports.default = Yuntongxun`
so, if you use es6+babel, you can use `import Yuntongxun from 'yuntongxun-sdk';`
others, you need `var Yuntongxun = require('yuntongxun-sdk').default;`

**Comment by soulwu** [comment]
like the example

``` js
import Yuntongxun from 'yuntongxun-sdk';

const yuntongxun = new Yuntongxun({
  urlPrefix: 'https://app.cloopen.com:8883',
  version: '2013-12-26',
  accountSid: '<Your accountSid>',
  authToken: '<Your authToken>',
  appId: '<Your appId>'
});

yuntongxun.voiceVerify('13700000000', '123456').then((callSid) => {
  console.log(callSid);
}, (err) => {
  console.error(err);
});
```
